#include "node_tree.hpp"
#include "ui_framework/node.hpp"
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <limits>
#include <memory>
#include <string>
namespace
{
struct TestFailure{std::string message;};
void expect(bool condition,const char* message){if(!condition)throw TestFailure{message};}
void expectNear(float actual,float expected,float epsilon,const char* message){if(std::fabs(actual-expected)>epsilon)throw TestFailure{message};}
class AnimationNode final:public ui::Node{public:ui::FloatAnimationProperty valueProperty()noexcept{return makeFloatAnimationProperty(value_,&value_);}float value()const noexcept{return value_;}private:float value_=0.0f;};
class DualAnimationNode final:public ui::Node{public:ui::FloatAnimationProperty xProperty()noexcept{return makeFloatAnimationProperty(x_,&x_);}ui::FloatAnimationProperty yProperty()noexcept{return makeFloatAnimationProperty(y_,&y_);}float x()const noexcept{return x_;}float y()const noexcept{return y_;}private:float x_=0.0f;float y_=100.0f;};
void test_linear_animation_advances_through_node_tree(){ui::NodeTree tree;auto node=std::make_unique<AnimationNode>();auto*p=node.get();tree.attachRoot(0,std::move(node));ui::AnimationController animations;animations.to(p->valueProperty(),10.0f,1.0f,ui::AnimationEasing::Linear);tree.advanceTime(0.25f);expectNear(p->value(),2.5f,0.0001f,"linear animation must interpolate after partial time advance");tree.advanceTime(0.75f);expectNear(p->value(),10.0f,0.0001f,"animation must reach target at duration");}
void test_easing_is_applied(){ui::NodeTree tree;auto node=std::make_unique<DualAnimationNode>();auto*p=node.get();tree.attachRoot(0,std::move(node));ui::AnimationController animations;animations.to(p->xProperty(),1.0f,1.0f,ui::AnimationEasing::EaseIn);animations.to(p->yProperty(),0.0f,1.0f,ui::AnimationEasing::EaseOut);tree.advanceTime(0.5f);expectNear(p->x(),0.25f,0.0001f,"EaseIn must square normalized time");expectNear(p->y(),25.0f,0.0001f,"EaseOut must interpolate independently from the current value");}
void test_same_property_replaces_previous_animation(){ui::NodeTree tree;auto node=std::make_unique<AnimationNode>();auto*p=node.get();tree.attachRoot(0,std::move(node));const auto property=p->valueProperty();ui::AnimationController animations;animations.to(property,10.0f,1.0f);tree.advanceTime(0.4f);expectNear(p->value(),4.0f,0.0001f,"first animation must advance before replacement");animations.to(property,8.0f,0.6f);tree.advanceTime(0.3f);expectNear(p->value(),6.0f,0.0001f,"replacement animation must start from current value");tree.advanceTime(0.3f);expectNear(p->value(),8.0f,0.0001f,"replacement animation must reach its new target");}
void test_different_properties_can_animate_concurrently(){ui::NodeTree tree;auto node=std::make_unique<DualAnimationNode>();auto*p=node.get();tree.attachRoot(0,std::move(node));ui::AnimationController animations;animations.to(p->xProperty(),100.0f,1.0f,ui::AnimationEasing::Linear);animations.to(p->yProperty(),0.0f,2.0f,ui::AnimationEasing::Linear);tree.advanceTime(0.5f);expectNear(p->x(),50.0f,0.0001f,"first property must advance independently");expectNear(p->y(),75.0f,0.0001f,"second property must advance independently");}
void test_cancel_keeps_current_value(){ui::NodeTree tree;auto node=std::make_unique<AnimationNode>();auto*p=node.get();tree.attachRoot(0,std::move(node));const auto property=p->valueProperty();ui::AnimationController animations;animations.to(property,10.0f,1.0f);tree.advanceTime(0.4f);animations.cancel(property);const float cancelled=p->value();tree.advanceTime(0.6f);expectNear(p->value(),cancelled,0.0001f,"cancel must leave the current property value unchanged");}
void test_zero_duration_applies_target_immediately(){ui::NodeTree tree;auto node=std::make_unique<AnimationNode>();auto*p=node.get();tree.attachRoot(0,std::move(node));const auto property=p->valueProperty();property.set(2.0f);ui::AnimationController animations;animations.to(property,7.0f,0.0f);expectNear(p->value(),7.0f,0.0001f,"zero-duration animation must apply target immediately");tree.advanceTime(1.0f);expectNear(p->value(),7.0f,0.0001f,"completed zero-duration animation must remain finished");}
void test_animation_property_becomes_invalid_when_node_is_destroyed(){ui::NodeTree tree;ui::FloatAnimationProperty property;{auto node=std::make_unique<AnimationNode>();auto*p=node.get();tree.attachRoot(0,std::move(node));property=p->valueProperty();ui::AnimationController animations;animations.to(property,10.0f,1.0f);tree.removeRoot(p);}tree.advanceTime(1.0f);expect(!property.isValid(),"property handle must become invalid after its owner is destroyed");expect(!ui::AnimationController{}.cancel(property),"invalid property must not cancel runtime animation");}
void test_non_finite_inputs_are_rejected_without_corrupting_state(){ui::NodeTree tree;auto node=std::make_unique<AnimationNode>();auto*p=node.get();tree.attachRoot(0,std::move(node));const auto property=p->valueProperty();ui::AnimationController animations;property.set(3.0f);animations.to(property,std::numeric_limits<float>::quiet_NaN(),1.0f);animations.to(property,8.0f,std::numeric_limits<float>::infinity());expectNear(p->value(),3.0f,0.0001f,"non-finite animation inputs must not corrupt the property");tree.advanceTime(std::numeric_limits<float>::quiet_NaN());tree.advanceTime(-1.0f);expectNear(p->value(),3.0f,0.0001f,"non-finite or negative time deltas must not advance rejected animations");}
void test_replacement_after_completed_frame_does_not_resurrect_old_animation(){ui::NodeTree tree;auto node=std::make_unique<AnimationNode>();auto*p=node.get();tree.attachRoot(0,std::move(node));const auto property=p->valueProperty();ui::AnimationController animations;animations.to(property,10.0f,0.5f);tree.advanceTime(0.5f);expectNear(p->value(),10.0f,0.0001f,"animation must complete on exact duration");animations.to(property,20.0f,0.5f);tree.advanceTime(0.25f);expectNear(p->value(),15.0f,0.0001f,"a replacement after completion must start from the final value only");tree.advanceTime(0.25f);expectNear(p->value(),20.0f,0.0001f,"completed replacement must reach its own target");}
}
int main(){try{test_linear_animation_advances_through_node_tree();test_easing_is_applied();test_same_property_replaces_previous_animation();test_different_properties_can_animate_concurrently();test_cancel_keeps_current_value();test_zero_duration_applies_target_immediately();test_animation_property_becomes_invalid_when_node_is_destroyed();test_non_finite_inputs_are_rejected_without_corrupting_state();test_replacement_after_completed_frame_does_not_resurrect_old_animation();}catch(const TestFailure& failure){std::cerr<<"Animation tests failed: "<<failure.message<<'\n';return EXIT_FAILURE;}std::cout<<"Animation tests passed\n";return EXIT_SUCCESS;}
